### ISSUE TITLE
Update Failing With Unknown Attribute Error

### ISSUE THREAD

**Issue by gordonbanderson** [manticoresoftware/manticoresearch-php#10]
hi,

Trying to write an update test, updating the only product with id 100.

https://github.com/gordonbanderson/manticoresearch-php/blob/testing/test/Manticoresearch/Endpoints/UpdateTest.php#L42

The error I get is

```
1) Manticoresearch\Test\Endpoints\UpdateTest::testUpdateProduct
Manticoresearch\Exceptions\ResponseException: {"type":"index products: attribute 'title' not found","index":"products"}

/var/www/html/manticoresearch-php/src/Manticoresearch/Transport/Http.php:123
/var/www/html/manticoresearch-php/src/Manticoresearch/Client.php:322
/var/www/html/manticoresearch-php/src/Manticoresearch/Client.php:208
/var/www/html/manticoresearch-php/test/Manticoresearch/Endpoints/UpdateTest.php:56
```

If I call describe endpoint prior to running this test I can see id, title and price.  Does attribute mean a column here?

Or if I have made a mistake please let me know.  But from the  documentation I think my approach is correct.

Regards

Gordon

**Comment by adriannuta** [comment]
`text` is a full-text field, changing them by `update` is not supported right now, only by document replacement (via `replace`). On `update` the engine looks only on attribute list (anything that's not a `text`).

**Comment by gordonbanderson** [comment]
Thanks for the feedback, appreciated.
