### ISSUE TITLE
Does manticoresearch-php support nested bool queries?

### ISSUE THREAD

**Issue by kroky** [manticoresoftware/manticoresearch-php#102]
https://manual.manticoresearch.com/Searching/Filters#Nested-bool-query

I fail to see it in the code. Since we are integrating that in Tiki as an Elasticsearch replacement (context here https://dev.tiki.org/Manticore-Search) I am going to build the nested syntax in the client anyway. Do you prefer a PR instead and are you willing to merge it if I submit one?

**Comment by sanikolaev** [comment]
Yes it does.

Here's the docs https://github.com/manticoresoftware/manticoresearch-php/blob/master/docs/query.md#boolquery

Here's a related test which can be used as an example https://github.com/manticoresoftware/manticoresearch-php/blob/master/test/Manticoresearch/SearchTest.php#L571

**Comment by kroky** [comment]
Alright, thanks! I wasn't sure how the search class accepts the query but now I see.
