### ISSUE TITLE
How to set match mode to SPH_MATCH_EXTENDED2 ?

### ISSUE THREAD

**Issue by marios88** [manticoresoftware/manticoresearch-php#105]
Hello i am in the process of migrating to manticore from an old sphinx installation but i cannot find any options on how to set match mode to SPH_MATCH_EXTENDED2, is it not supported?

Here is part of the old code for reference
```
    $sphinx = new SphinxClient;
    $sphinx->SetServer('localhost', 9312);
    $sphinx->SetMatchMode(SPH_MATCH_EXTENDED2);
    $sphinx->SetRankingMode(SPH_RANK_EXPR,'sum((4*lcs+2*(min_hit_pos==1)+exact_hit)*user_weight)*1000 + IF(IN(f1, "1"), 0, 10000) + IF(IN(f2, "1"), 0, 10000) + bm25');
    $sphinx->SetFieldWeights(['email' => 0]);
    $sphinx->Query($s, 'index0')['matches'];
```

**Comment by sanikolaev** [comment]
SPH_MATCH_EXTENDED2 [was temporary even in Sphinx](https://github.com/sphinxsearch/sphinx/blob/master/api/sphinxapi.php#L66). It's not supported in Manticore, at least officially (nothing about it in the docs https://manual.manticoresearch.com/)

You can use `option()` to specify search options including ranking options. See https://github.com/manticoresoftware/manticoresearch-php/blob/master/docs/searchclass.md#option
