### ISSUE TITLE
Feature requests: multi-attribute sorting and case-insensitive sort directions

### ISSUE THREAD

**Issue by Robert-K-S** [manticoresoftware/manticoresearch-php#109]
With regard to the `sort()` function in the `Search` class, I would like to be able to specify multi-attribute sorting, like so:    
    
`$search->sort(['date' => 'DESC', 'attribute2' => 'ASC', 'attribute3' => 'DESC', 'attribute4' => 'ASC']);`    
    
It appears that the current code only allows for specifying sorting by one attribute, or by multiple attributes but all with the same sort direction.    
    
It also appears that specifying the sort direction (`'ASC'` or `'DESC'`) as anything other than all-lowercase results in an error.  It would be preferable to be able to specify these in uppercase, consistent with SQL conventions.

**Comment by githubmanticore** [comment]
➤ Nick Sergeev commented:
 

 
The support of uppercase sorting directions is implemented in https://github.com/manticoresoftware/manticoresearch-php/releases/tag/v2.3.1 
 
As for the use of multi-attribute sorting, you can do it by chaining multiple `sort` calls, e.g.: 
 
``` 
$search->sort(['date' => 'DESC'])->sort(['attribute2' => 'ASC'])->sort(['attribute3' => 'DESC']); 
```

**Comment by githubmanticore** [comment]
➤ Nick Sergeev commented:
 

 
We've updated the documentation on sorting and fixed the typo.

**Comment by sanikolaev** [comment]
> What is the difference between

Please review the code https://github.com/manticoresoftware/manticoresearch-php/blob/051e90d9b9421601c3188afceceb568765984e3a/src/Manticoresearch/Search.php#L273

> How to dump the query?

What do you mean?

**Comment by sanikolaev** [comment]
The PHP client generates a JSON query, not SQL. You should be able to intercept it before sending to Manticore and `print_r()`. I believe it can be done somewhere here https://github.com/manticoresoftware/manticoresearch-php/blob/master/src/Manticoresearch/Transport/Http.php
