### ISSUE TITLE
Allow to user filter with BOOL condition

### ISSUE THREAD

**Issue by dgastudio** [manticoresoftware/manticoresearch-php#113]
Hi.  
  
Quite often there is a need to use filters with an OR condition.  
  
At the moment, this feature is available when using queries, but not when using filters.  
  
$bool2 = new \Manticoresearch\Query\BoolQuery();  
$bool2->should(new \Manticoresearch\Query\('year', 2000));  
$bool2->should(new \Manticoresearch\Query\('year', 2010));  
$bool->must($bool2);  
  
it will be great if you can integrate this feature into this awesome project.  
Thank you

**Comment by marclaporte** [comment]
This is in https://github.com/manticoresoftware/manticoresearch-php/releases/tag/v2.3.1
