### ISSUE TITLE
Inserting documents quits every time at 423908 inserts

### ISSUE THREAD

**Issue by ghost** [manticoresoftware/manticoresearch-php#116]
Hi,

Rebuilding my search indexes after upgrading from 5.x to 6.x and out of 8M rows it now quits at 423908 rows. I reverted back to Manticore 5.0.2 but same issue.

Tried both PHP 8.1 and 8.2. No errors anywhere in PHP or Manticore.

I did change from using SphinxSE to using HTTP. But I do not see how that could cause this issue. Any idea?

**Comment by sanikolaev** [comment]
Probably closed in favor of https://github.com/manticoresoftware/manticoresearch/issues/1089
