### ISSUE TITLE
Multiple boolean operators don't work with this package and Manticore 5.x

### ISSUE THREAD

**Issue by ghost** [manticoresoftware/manticoresearch-php#118]
It seems that when using this PHP library with Manticore 5.0.2 makes multiple boolean operators return 0 results. It does work on 6.0.4 however.

When I try it with raw SQL commands I get the correct results but the same query with PHP returns no results.

Also the following code produces the error:
`"index index_rt: query error: query is non-computable (node consists of NOT operators only)"`

```php
$config = ['host' => 'manticore', 'port' => '9308'];
$client = new Client($config);
$search = new Search($client);
$search->setIndex('index_rt');

$field = 'searchname';
$query = 'Dave -Jones -Smith';
$query = sprintf('@@relaxed @%s %s', $field, $query);

// Generated search query above is: "@@relaxed @searchname Dave -Jones -Smith"

$results = $search->search($query)->get();

foreach ($results as $hit) {
    echo $hit->searchname;
}
```

**Comment by tomatolog** [comment]
seems issue fixed after 604-release?

**Comment by sanikolaev** [comment]
> 
 So at least 3.x version of this package is not compatible with Manticore versions < 6.x

It's not supposed to be compatible: 


https://github.com/manticoresoftware/manticoresearch-php#requirements

<img width="883" alt="image" src="https://user-images.githubusercontent.com/28719845/231099865-771051e5-639f-4f3a-94da-aeab9dd06d4d.png">
