### ISSUE TITLE
Filter does not work with bool fields as expected

### ISSUE THREAD

**Issue by someson** [manticoresoftware/manticoresearch-php#122]
```  
CREATE TABLE IF NOT EXISTS tableName (  
...  
is_active bool,  
...  
)...  
```  
  
Fails:  
```php  
$search->filter('is_active', 'equals', true);  
$results = $search->get(); // thows exception  
```  
  
Actually works:  
```php  
$search->filter('is_active', 'equals', 1);  
```  
  
There's nothing mentioned in the documentation.  
There's no any TestCase in `\Manticoresearch\Test\SearchTest`

**Comment by githubmanticore** [comment]
➤ Nick Sergeev commented:
 

 
Fixed in https://github.com/manticoresoftware/manticoresearch-php/commit/732e6dc202bfb359351241dfda7803ba779fda3c
