### ISSUE TITLE
Ordering in facet result

### ISSUE THREAD

**Issue by AnticaAndrey** [manticoresoftware/manticoresearch-php#125]
Please make it possible to sort the output of faceted search by count
https://manual.manticoresearch.com/Searching/Faceted_search#Ordering-in-facet-result

Thanks!

**Comment by Nick-S-2018** [comment]
Added in https://github.com/manticoresoftware/manticoresearch-php/commit/d4af5655d580c9b6603b6a47504b1465d57ce8f6
