### ISSUE TITLE
Escape characters in SearchClass

### ISSUE THREAD

**Issue by Kayrim** [manticoresoftware/manticoresearch-php#126]
Would be great to build in an escape feature in the search class as some unescaped queries could lead to unexpected behavior. Personally handling myself but would be nice if it was built in as part of the config.

From Sphinx:
```php
	function EscapeString ( $string )
	{
		$from = array ( '\\', '(',')','|','-','!','@','~','"','&', '/', '^', '$', '=', '<' );
		$to   = array ( '\\\\', '\(','\)','\|','\-','\!','\@','\~','\"', '\&', '\/', '\^', '\$', '\=', '\<' );

		return str_replace ( $from, $to, $string );
	}
``` 

Im currently working around it like so:

```php
<?php
use Manticoresearch\Search;
class CustomManticoreSearch extends Search
{
    /**
     * Escape a string for use in a query string, manticore currently doesn't implement this.
     * @param string $string
     * @return string
     * 
     */
    public function escapeString(string $string): string
    {
        $from = array('\\', '(', ')', '|', '-', '!', '@', '~', '"', '&', '/', '^', '$', '=', '<', "'");
        $to   = array('\\\\', '\(', '\)', '\|', '\-', '\!', '\@', '\~', '\"', '\&', '\/', '\^', '\$', '\=', '\<', "\\'");

        return str_replace($from, $to, $string);
    }
}
``` 

Thanks again for the lib.

**Comment by Nick-S-2018** [comment]
You can now use the `Manticoresearch\Utils` trait which has the similar `escape` function.  Or do you want this to be implemented exactly as a config option?

**Comment by Kayrim** [comment]
> You can now use the `Manticoresearch\Utils` trait which has the similar `escape` function. Or do you want this to be implemented exactly as a config option?

No that should be enough, will help avoid input errors 👍🏽
