### ISSUE TITLE
Incorrect PHP DocBlock in class \Manticoresearch\Search

### ISSUE THREAD

**Issue by andrey-tech** [manticoresoftware/manticoresearch-php#128]
# Version affected

3.0.1

# Description

Method `search()` of class `\Manticoresearch\Search` has incorrect PHP DocBlock: parameter `$queryString` has incomplete type `string`, because "this method accepts either a full-text match string or a BoolQuery object". So I get an errors from static analyzer Psalm in my code.

```php
    /**
     * @param string $queryString
     * @return $this
     */
    public function search($queryString): self
```
# Possible solution

Fix type of parameter `$queryString` in PHP DocBlock:

```php
    /**
     * @param string|BoolQuery $queryString
     * @return $this
     */
    public function search($queryString): self
```

**Comment by sanikolaev** [comment]
Hi. Would you like to make a PR with this change?

**Comment by sanikolaev** [comment]
Done in https://github.com/manticoresoftware/manticoresearch-php/pull/129
