### ISSUE TITLE
ExceptionInterface does not extends Throwable

### ISSUE THREAD

**Issue by andrey-tech** [manticoresoftware/manticoresearch-php#130]
# Version affected
3.0.1

# Description

The interface `\Manticoresearch\Exceptions\ExceptionInterface` **does not extends** interface `\Throwable`, therefore I can't use `ExceptionInterface` to catch any Manticore Search exceptions:

```php
try {
   ...
} catch (\Manticoresearch\Exceptions\ExceptionInterface $exception) {
   ...
}
```

So I get an errors from static analyzer Psalm in my code: 
> psalm: InvalidCatch: Class/interface Manticoresearch\Exceptions\ExceptionInterface cannot be caught

# Possible solution

Fix interface `\Manticoresearch\Exceptions\ExceptionInterface`:

```php
/**
 * Interface ExceptionInterface
 * @package Manticoresearch\Exceptions
 */
interface ExceptionInterface extends \Throwable
{
}
```

**Comment by Nick-S-2018** [comment]
Done in https://github.com/manticoresoftware/manticoresearch-php/pull/131
