### ISSUE TITLE
Server path

### ISSUE THREAD

**Issue by aivchen** [manticoresoftware/manticoresearch-php#135]
Currently there is no way to specify a path in the connection config.
For example, if my manticore server is behind nginx proxy and I want to access to it via http://localhost/manticore there is no way to do it.
Would be cool to have something like this:
```php
$config = ['host'=>'localhost','port'=>80, 'path'=>'/manticore'];
$client = new \Manticoresearch\Client($config);
```

**Comment by sanikolaev** [comment]
Nice idea! Shouldn't be a big deal to implement and should work as long as Nginx can do `/manticore/smth => /smth` redirects.

@aivchen would you like to change it yourself in the client (with our assistance) and create a PR?

**Comment by aivchen** [comment]
Yup, I'll try to implement it.

**Comment by sanikolaev** [comment]
Great. Feel free to ping us here in case you can't understand how this or that is done in the client. We'll be happy to assist.

**Comment by Nick-S-2018** [comment]
We've approved [the corresponding PR](https://github.com/manticoresoftware/manticoresearch-php/pull/136) from @aivchen  which solves this issue.
