### ISSUE TITLE
PHP Code Style

### ISSUE THREAD

**Issue by aivchen** [manticoresoftware/manticoresearch-php#137]
As I see php code style is very various across the project.
How about replacing PHP_CodeSniffer with Php-Cs-Fixer? The latter is very flexible, easy to set up and allows to fine tune almost any aspect of php code.
Also I see that PHP_CodeSniffer is configured for PSR-2 checking. But PHP-FIG has released PSR-12 and PER - more strict standards. How about switching to PSR-12/PER?

**Comment by sanikolaev** [comment]
Thanks for the suggestion @aivchen 

@Nick-S-2018 @donhardman Please think about it.

**Comment by sanikolaev** [comment]
The related PR https://github.com/manticoresoftware/manticoresearch-php/pull/141 has been approved and merged. The change will be includes in the upcoming release. Thank you for the contribution @aivchen!

**Comment by aivchen** [comment]
#141 is not related. In #141 we just refactored PHP_CodeSniffer. But we still follow PSR-2.
In this issue I suggest switching from PSR-2 to PSR-12 or PER.

**Comment by Nick-S-2018** [comment]
Ok, no objections from me

**Comment by sanikolaev** [comment]
OK. I don't object too. Now we need to make the code compatible with it. I've asked @aivchen in https://github.com/manticoresoftware/manticoresearch-php/pull/148 if he'd like to help with that.

**Comment by aivchen** [comment]
Done: #148
