### ISSUE TITLE
Drop support for older versions of php

### ISSUE THREAD

**Issue by aivchen** [manticoresoftware/manticoresearch-php#143]
PHP 7.1 - 7.4 are not supported by php core developers.
PHP 8.0  will stop to be supported in November 2023.

I suggest to drop support for all < 8.1 php versions in next major release.
It would allow to use strict types for variables, parameters, use readonly properties etc. 

What do you think?

**Comment by sanikolaev** [comment]
Thank you for bringing up this idea!

According to [https://stitcher.io/blog/php-version-stats-january-2023](https://stitcher.io/blog/php-version-stats-january-2023), at the beginning of the year, approximately a quarter of PHP users were using PHP 7.4, and only 23% of the top 1,000 popular packages required a version >= 8.

It would be beneficial to find updated statistics. However, if the numbers haven't changed significantly, it seems premature to drop support.

**Comment by aivchen** [comment]
https://packagist.org/php-statistics

For September 2023:
![image](https://github.com/manticoresoftware/manticoresearch-php/assets/4580308/feee7f31-ef43-41c1-87c6-034e057f7a7a)

I think we can drop support for php < 7.4. What do you think?

**Comment by sanikolaev** [comment]
According to https://github.com/manticoresoftware/manticoresearch-php#requirements , the latest releases of the client already support PHP >= 7.4.

**Comment by aivchen** [comment]
Yes, but in [composer.json](https://github.com/manticoresoftware/manticoresearch-php/blob/6b28539ba6e38672e68b9eba5365bff0b9f11140/composer.json#L8) the requirement is php >= 7.1.

**Comment by sanikolaev** [comment]
> Yes, but in [composer.json](https://github.com/manticoresoftware/manticoresearch-php/blob/6b28539ba6e38672e68b9eba5365bff0b9f11140/composer.json#L8) the requirement is php >= 7.1.

@Nick-S-2018 is this a mistake?

**Comment by aivchen** [comment]
Technically, this is a mistake in the documentation, because the code is more important than the documentation. Currently, all versions of manticoresearch-php can be used in any project running on php >=7.1.

**Comment by Nick-S-2018** [comment]
Done in https://github.com/manticoresoftware/manticoresearch-php/commit/7ec10d479d0c9980cc14379c34d26de13a4a559b
