### ISSUE TITLE
The first request is not search request if using basic auth

### ISSUE THREAD

**Issue by vipercs90** [manticoresoftware/manticoresearch-php#146]
php version 8.2
manticoresearch-php version 3.1.0

Client config

```
$params = [
    'connections' =>
        [
            [
                'host' => 'host',
                'port' => 80,
                'timeout' => 5,
                'connection_timeout' => 1,
                'transport' =>  'Http',
                'scheme' => 'http',
                'username' => 'login',
                'password' => 'password',
                'curl' => [
                    CURLOPT_FAILONERROR => true,
                ],
                'persistent' => true
            ],
        ]
];
```

Nginx  1.25.2 as proxy to http manticore api
Nginx location config
```
location / {
   auth_basic "Manticoresearch Area";
   auth_basic_user_file /etc/nginx/.htpasswd;
   proxy_pass http://127.0.0.1:9308;
}
```
Screenshot of requests in fiddler
![image](https://github.com/manticoresoftware/manticoresearch-php/assets/5518560/3d291a56-dc82-43a4-84f7-06513b623643)
![image](https://github.com/manticoresoftware/manticoresearch-php/assets/5518560/738b4bf3-2ab8-49c4-96cf-b24943aaafe1)

The first query is not a search query, where does it come from? (n+1 requests)
If the parameter persistance = false is specified, then such a request will occur for every search request! (n*2 requests)

The problem is that we have a corporate firewall that blocks traffic if there are a lot of 401 errors from the service because it perceives this as a brute force attack.

**Comment by vipercs90** [comment]
in Manticoresearch\Transport\Http
```
if ($connection->getConfig('username') !== null && $connection->getConfig('password') !== null) {
            curl_setopt($conn, CURLOPT_HTTPAUTH, CURLAUTH_ANY); <------- this added request 
            curl_setopt(
                $conn,
                CURLOPT_USERPWD,
                $connection->getConfig('username').":".$connection->getConfig('password')
            );
        }
```

**Comment by sanikolaev** [comment]
Hello @vipercs90 

Sorry I don't understand the issue. 

> The first query is not a search query, where does it come from? (n+1 requests)

What query do you mean? This one?
![image](https://github.com/manticoresoftware/manticoresearch-php/assets/28719845/8b6cd005-04df-42b5-931f-cbd1364e1cde)

**Comment by vipercs90** [comment]
![image](https://github.com/manticoresoftware/manticoresearch-php/assets/5518560/b50aa441-10da-4459-8daa-5214bc659c10)
![image](https://github.com/manticoresoftware/manticoresearch-php/assets/5518560/bf00890b-1df0-4e90-a043-878c63a66287)
https://github.com/manticoresoftware/manticoresearch-php/issues/146#issuecomment-1771136715

**Comment by vipercs90** [comment]
Curl sends two requests to the server instead of one.

because of this
curl_setopt($conn, CURLOPT_HTTPAUTH, CURLAUTH_ANY);

**Comment by vipercs90** [comment]
Lots of 401s cause the firewall to block traffic

**Comment by sanikolaev** [comment]
Thanks. It's clear now. We'll look into this. If you can think of a change which fixes this, feel free to make a pull request.

**Comment by vipercs90** [comment]
I found a solution to the problem
```
$params = [
    'connections' =>
        [
            [
                'host' => 'host',
                'port' => 80,
                'timeout' => 5,
                'connection_timeout' => 1,
                'transport' =>  'Http',
                'scheme' => 'http',
                'username' => 'login',
                'password' => 'password',
                'curl' => [
                    CURLOPT_FAILONERROR => true,
                    CURLOPT_HTTPAUTH => CURLAUTH_BASIC, // this replaces CURLAUTH_ANY
                ],
                'persistent' => true
            ],
        ]
];
```
A little unobvious solution but quite logical.

**Comment by sanikolaev** [comment]
Reopened as it seems that we can make the behaviour less confusing by default.
