### ISSUE TITLE
`getDocumentByIds` returns not all documents when size of array > 20

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticoresearch-php#174]
This code only retrieves 20 documents, and currently, we don't have the option to chain a limit setting in the Client. However, I believe we shouldn't need to. We have an array of IDs, which should allow us to determine the necessary limit to fetch all the documents.

```
$index->getDocumentByIds($ids); # Only 20 returns even when ids contains more
```

Currently, it's not functioning. The solution is simply to set the limit to the size of the $ids array.

**Comment by donhardman** [comment]
The fix can be found here: https://github.com/manticoresoftware/manticoresearch-php/pull/175

But I think it's a good idea to check whether this is the only place that needs modification and to ensure we don't have a similar issue elsewhere.

**Comment by sanikolaev** [comment]
Let's add a test for "returns not all documents when size of array > 20".

**Comment by Nick-S-2018** [comment]
Done in https://github.com/manticoresoftware/manticoresearch-php/commit/84281631b6f311925005201e3de20132f2f85669
