### ISSUE TITLE
Add support of method chaining for knn

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticoresearch-php#184]
We need to enable method chaining with the KNN request in the client because we've decided to add vector search to our GitHub Issue Search Demo. To simplify the process, it would be great to have an easier way to perform both KNN and full-text searches using the PHP client.

The documentation can be found here is https://manual.manticoresearch.com/dev/Searching/KNN#KNN-vector-search

**Comment by sanikolaev** [comment]
Blocker for continuing with the demo.

**Comment by sanikolaev** [comment]
Blocked by https://github.com/manticoresoftware/manticoresearch/issues/1662

**Comment by sanikolaev** [comment]
> Blocked by https://github.com/manticoresoftware/manticoresearch/issues/1662

Done

**Comment by Nick-S-2018** [comment]
Done in https://github.com/manticoresoftware/manticoresearch-php/commit/552e3b1156eed2ad4fc027e23de54a957890d09f, https://github.com/manticoresoftware/manticoresearch-php/commit/ad3e2e6f4ca7df24112658f377b9d34c296267bc
