### ISSUE TITLE
Wrong Runtime Exception Thrown

### ISSUE THREAD

**Issue by gordonbanderson** [manticoresoftware/manticoresearch-php#19]
hi,

This appears inconsistent with other parts of the code base that throw a `Manticoresearch\Exceptions\RuntimeException`

https://github.com/manticoresoftware/manticoresearch-php/blob/master/src/Manticoresearch/Connection.php#L215

It is throwing a `\RuntimeException` instead

Cheers

Gordon

**Comment by githubmanticore** [comment]
fix #19 wrong RuntimeException in Connection via commit https://github.com/manticoresoftware/manticoresearch-php/commit/94c40d43d3e17dbf9baae87eb30f9298dca36359

**Comment by githubmanticore** [comment]
fix #19 wrong RuntimeException in Connection via commit https://github.com/manticoresoftware/manticoresearch-php/commit/94c40d43d3e17dbf9baae87eb30f9298dca36359
