### ISSUE TITLE
NICK will remove https://github.com/manticoresoftware/manticoresearch-php/blob/master/CHANGELOG.md

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/manticoresearch-php#202]
https://github.com/manticoresoftware/manticoresearch-php/blob/master/CHANGELOG.md

**Comment by Nick-S-2018** [comment]
Done in https://github.com/manticoresoftware/manticoresearch-php/commit/54daf5e79cbe17e2c3666acc1765648ed73b1c87
