### ISSUE TITLE
NICK will fix the example related with "new Match"

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/manticoresearch-php#203]
In the docs we say:
![image](https://github.com/manticoresoftware/manticoresearch-php/assets/28719845/7ee727e4-91f7-4b13-b0cf-58ef9f7cdae3)

However `new Match` is not working:
```
PHP Parse error:  syntax error, unexpected token "match", expecting ":" in /Users/sn/test.php on line 18
```

As discussed, we need to update the docs.

**Comment by Nick-S-2018** [comment]
Fixed in https://github.com/manticoresoftware/manticoresearch/commit/34fbb782d0c4424046dff7264fe5961f4945ea66
