### ISSUE TITLE
MatchPhrase Document Minorly Incorrect

### ISSUE THREAD

**Issue by gordonbanderson** [manticoresoftware/manticoresearch-php#21]
hi,

In https://github.com/manticoresoftware/manticoresearch-php/blob/master/docs/query.md the example for `MatchPhrase` is incorrect.  Testing a different index locally Manticore returns an error if the comma separated values have a space in them.

```
$bool->must(new \Manticoresearch\Query\MatchPhrase('team of exlorers', 'title, content'));
```
should be
```
$bool->must(new \Manticoresearch\Query\MatchPhrase('team of exlorers', 'title,content'));
```

Cheers

Gordon

**Comment by gordonbanderson** [comment]
Oh, and should exlorers be explorers?

**Comment by adriannuta** [comment]
Fixed. There was also an issue in Search and phrase() was using Match().

Yes, the list of fields must not have spaces between name and separator (comma).
