### ISSUE TITLE
Add AUTOCOMPLETE endpoint support

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticoresearch-php#212]
We should add the newly introduced `autocomplete` endpoint because currently we are unable to call it with the endpoints exposed right now.

**Comment by donhardman** [comment]
Implemented and tested at this pull request: https://github.com/manticoresoftware/manticoresearch-php/pull/213

**Comment by donhardman** [comment]
@Nick-S-2018 Could you please check if I've implemented this correctly? If so, would you mind reviewing the pull request?

**Comment by Nick-S-2018** [comment]
@donhardman  I've approved the PR, we can merge it.

**Comment by donhardman** [comment]
Closing the issue since it has been merged.
