### ISSUE TITLE
Update vs replace vs partial replace

### ISSUE THREAD

**Issue by stevenbrookes** [manticoresoftware/manticoresearch-php#216]
Hi

I'd like to be able to update one columnar attribute in an existing record.  I've tried the following via the API

* Update - doesn't work as it's a columnar attribute
* Replace - updates the files I want to update, but nulls/zeroes any data I don't pass in.  As there are a fair few attributes, I would have to search for the document, copy the data I want to keep and then make the replace call.  Seems wasteful as this could all be done on the server end without two roundtrips.
* Partial update - seems like this will do what I want but not currently part of the PHP library.  Is there any reason for it not to be supported as would seem to be the correct solution for my case.  I'm happy enough to provide patch if helpful.

Thanks for your thoughts and manticore!

**Comment by djklim87** [comment]
Have you tried [REPLACE + SET](https://manual.manticoresearch.com/dev/Data_creation_and_modification/Updating_documents/REPLACE#SQL-REPLACE)?

**Comment by stevenbrookes** [comment]
No I haven't - is there an API call for that - can you point me to the documentation?  I'd like to  avoid making two round trips to the server to in effect get the current record and then set the modified record.  I only want to change one attribute in the record so it seems odd to have to do two calls!

**Comment by tomatolog** [comment]
there is no update for columnar attributes that is why you should get the full row from the dockstore back to client or buddy then post the full document back via `replace` .

That is why you have to use https://manual.manticoresearch.com/dev/Data_creation_and_modification/Updating_documents/REPLACE#SQL-REPLACE with Buddy support or switch to non columar attributes is you need to use UPDATE.

I also wanted to notice that any update also disables secondary index on that attribute that could cause the slower filtering for updated attribute.

**Comment by stevenbrookes** [comment]
Could you comment on partial replace mentioned here  https://manual.manticoresearch.com/Data_creation_and_modification/Updating_documents/REPLACE#JSON-REPLACE

Partial replace:
POST /<table name>/_update/<id>
{
"<field1>": <value1>,
...
"<fieldN>": <valueN>
}

That seems to do what I want as it's replace rather than update.  I can't see support for it in the PHP library though.

**Comment by tomatolog** [comment]
here is a update example https://github.com/manticoresoftware/manticoresearch-php/tree/bc22ea5b2f18e755dd751da9a24d0c5440569f8d?tab=readme-ov-file#update-documents

**Comment by stevenbrookes** [comment]
That endpoint seems to use POST /json/update whereas partial replace is POST /json/_update   I dunno if they are the same thing internally to manticore though.  I think I'll run a test using Postman and see what that shows.

**Comment by tomatolog** [comment]
`_update` does not have mapping into any API

**Comment by stevenbrookes** [comment]
Ah OK.  Thanks for the support.  I guess a get/set approach is the best we can do for the moment.
