### ISSUE TITLE
Is it time for a new release?

### ISSUE THREAD

**Issue by marclaporte** [manticoresoftware/manticoresearch-php#219]
It has been over 1 year and 60 commits since the last release:
https://github.com/manticoresoftware/manticoresearch-php/compare/3.1.0...master

Thanks!

**Comment by sanikolaev** [comment]
@Nick-S-2018 Please review the commits and determine if we can release any new features or bug fixes that are not related to the changes in the daemon (which will be released after the new daemon version is available).

**Comment by Nick-S-2018** [comment]
Published: https://github.com/manticoresoftware/manticoresearch-php/releases/tag/3.2.0
