### ISSUE TITLE
Exception - column 'id' specified twice

### ISSUE THREAD

**Issue by rim89** [manticoresoftware/manticoresearch-php#220]
- Manticore 6.3.6
- manticoresoftware/manticoresearch-php v 3.1

Hi, when I add new document, like this

```php
$index->addDocument([
    'id' => $post->id,
    'name' => $post->name,
    'description' => $post->description,
]);
```
OR
```php
$index->addDocument([
    'id' => $post->id,
    'name' => $post->name,
    'description' => $post->description,
], $post->id);
```

I get an ResponseException

```json
{"type":"column 'id' specified twice","index":"posts"}
```

If remove 'id' key from $data array the error is gone.

**Comment by Nick-S-2018** [comment]
Yes, this is a correct behavior.  Specifying document ids inside `doc` data objects is not supported for `AddDocument`, so you must pass it as a separate argument.
