### ISSUE TITLE
Minor Error in Cluster Documentation

### ISSUE THREAD

**Issue by gordonbanderson** [manticoresoftware/manticoresearch-php#31]
In https://github.com/manticoresoftware/manticoresearch-php/blob/master/docs/cluster.md

The title for the documentation to delete a cluster is 'Create'

**Comment by githubmanticore** [comment]
fix #31 delete cluster docs via commit https://github.com/manticoresoftware/manticoresearch-php/commit/e2498235ef744cffc5e4c17a6d6f33a2e559d828

**Comment by githubmanticore** [comment]
fix #31 delete cluster docs via commit https://github.com/manticoresoftware/manticoresearch-php/commit/e2498235ef744cffc5e4c17a6d6f33a2e559d828
