### ISSUE TITLE
Coding Standards Compliance

### ISSUE THREAD

**Issue by gordonbanderson** [manticoresoftware/manticoresearch-php#36]
hi Adrian,

Firstly I do not with to add a PR for this as my stats would be unfairly over the codebase.  However I normally use phpcs and phpcbf to detect and fix errors against the PSR2 coding standard.

Locally I have ran these commands

1) Automated adherence to coding standards
```bash
vendor/bin/phpcbf --standard=PSR2 src/ test/
```
This alters source code so please ensure that it is backed up prior to running these commands.

2) Whilst one of the Travis tasks I added checks for coding standards, I have set it to not fail.  If the above command is run over the codebase, then the PHP_CS task in Travis can be set to this, which will fail the build if coding standards are not adhered to.
```
vendor/bin/phpcs --standard=PSR2 src/ test/
```
Running locally the warnings the command is picking up mostly long lines, and also tests with missing namespaces.  For example:
```
FILE: /var/www/html/manticoresearch-php/test/Manticoresearch/Endpoints/SearchTest.php
-----------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------
 6 | ERROR | Each class must be in a namespace of at least one level (a top-level vendor name)
-----------------------------------------------------------------------------------------------
```

In my professional experience using `phpcs` and `phpcbf` is a good thing to do.

Cheers

Gordon

**Comment by adriannuta** [comment]
Done.

**Comment by gordonbanderson** [comment]
Cool, thanks.  I'll create a separate PR to make Travis fail is code compliance fails.
