### ISSUE TITLE
Unable to Create Cluster

### ISSUE THREAD

**Issue by gordonbanderson** [manticoresoftware/manticoresearch-php#37]
hi Adrian,

I am trying to get clusters working with Travis, but have run into a problem in trying to create a cluster.

The relevant code is here, https://github.com/gordonbanderson/manticoresearch-php/blob/CLUSTER/test/ClusterTest.php

The output of a relevant Travis job, https://travis-ci.org/github/gordonbanderson/manticoresearch-php/jobs/682702724#L454, and indicates an error thus:

```bash
only SELECT queries are supported
```

I cannot find this in the manticore search PHP code, so I can only assume this is being returned by the Manticoresearch server?

Cheers

Gordon

**Comment by adriannuta** [comment]
The issue there was the cluster endpoints were childs of Sql instead of EmulateBySql (this just set mode=raw to allow non-selects to work via /sql). 
Testing this section would require 2 instances (you can create a cluster with one node, but you need 2 for test joining).

**Comment by gordonbanderson** [comment]
hi Adrian,

Thanks for the tip regarding more=raw, will give it a whirl.

Already got 2 manticoresearch services in the Travis file https://github.com/gordonbanderson/manticoresearch-php/blob/CLUSTER/.travis.yml#L23 :)

I'll configure it with a flag that will enable / disable cluster tests, and set one of the Travis builds to test the cluster, in a similar manner to using the alternative PHP Http transport mechanism.  Codecov I think merges test results together, and having a flag means that local unit testing will not be affected.

Cheers

Gordon

**Comment by gordonbanderson** [comment]
hi Adrian,

I appear to be past the cluster creation issue.  Next problem :)

With both of the testAlter* methods, https://github.com/gordonbanderson/manticoresearch-php/blob/CLUSTER/test/ClusterTest.php#L34, I am getting this error, see https://travis-ci.org/github/gordonbanderson/manticoresearch-php/builds/683586223#L396:

```
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Created cluster testcluster

Array

(

    [total] => 0

    [error] => 

    [warning] => 

)

ALTER: CLUSTER=testcluster

EALTER: CLUSTER=testcluster

E.............................................................  63 / 232 ( 27%)

...........................S..........S........................ 126 / 232 ( 54%)

............................................................... 189 / 232 ( 81%)

...........................................                     232 / 232 (100%)

Time: 8.34 seconds, Memory: 8.00 MB

There were 2 errors:

1) Manticoresearch\Test\ClusterTest::testAlterDropWithoutAdd

Manticoresearch\Exceptions\RuntimeException: Cluster name is missing.

/home/travis/build/gordonbanderson/manticoresearch-php/src/Manticoresearch/Endpoints/Cluster/Alter.php:45

/home/travis/build/gordonbanderson/manticoresearch-php/src/Manticoresearch/Cluster.php:37

/home/travis/build/gordonbanderson/manticoresearch-php/test/ClusterTest.php:46

2) Manticoresearch\Test\ClusterTest::testAlterAddThenDrop

Manticoresearch\Exceptions\RuntimeException: Cluster name is missing.

/home/travis/build/gordonbanderson/manticoresearch-php/src/Manticoresearch/Endpoints/Cluster/Alter.php:45

/home/travis/build/gordonbanderson/manticoresearch-php/src/Manticoresearch/Cluster.php:37

/home/travis/build/gordonbanderson/manticoresearch-php/test/ClusterTest.php:62

ERRORS!

Tests: 232, Assertions: 352, Errors: 2, Skipped: 2.
```


I am confused as to why I am getting the error message `Cluster name is missing`

Regards

Gordon

**Comment by adriannuta** [comment]
Because of https://github.com/gordonbanderson/manticoresearch-php/blob/master/src/Manticoresearch/Endpoints/Cluster/Alter.php#L20  ( must be $this->cluster).

Btw, don't set  `mode=raw` to cluster()->create(), it's not needed, just the class to extend  EmulateBySql

**Comment by gordonbanderson** [comment]
hi Adrian,

I suspect I used `mode=raw` prior to you making the change to extend `EmulateBySql`.  See https://travis-ci.org/github/gordonbanderson/manticoresearch-php/builds/683607689 for report (note that I temporarily removed the other Travis tests from the matrix to speed things up, as I am testing this entirely through Travis), as https://github.com/gordonbanderson/manticoresearch-php/blob/CLUSTER/test/ClusterTest.php is now passing.  As in the alter tests are passing (as well as implicitly create and delete cluster).

Just a thought but if the creation of the `$client` variable is centralized in the test suite (aka anywhere were `MS_HOST` and `MS_PORT` are used), then perhaps the full test suite can be run once for cluster mode using each of the Http transport options, perhaps via a (suggested name) `CLUSTERED=1` variable, but default to current behavior if that variable is missing.  I am still learning cluster mode, and it looks like newly created indexes would also need centralized in order that they may optionally be replicated to the cluster.

My idea of a Travis matrix is this, namely run the different versions of PHP against a single instance, run the code quality tests, run one PHP version test against different Http transport,  and then run the tests in clustered mode with both forms of Http transport.

```
matrix:
  include:
    - php: 7.1
      env: PHPUNIT_TEST=1
    - php: 7.2
      env: PHPUNIT_COVERAGE_TEST=1
    - php: 7.2
      env: PHPCS_TEST=1
    - php: 7.3
      env: PHPUNIT_TEST=1
    - php: 7.4
      env: PHPUNIT_TEST=1
    - php: 7.4
      env: PHPUNIT_TEST=1 TRANSPORT=PhpHttp
    - php: 7.4
      env: PHPSTAN_TEST=1
    - php: 7.4
      env: PHPUNIT_TEST=1 CLUSTERED=1
    - php: 7.4
      env: PHPUNIT_TEST=1 TRANSPORT=PhpHttp CLUSTERED=1
 ```

Possible?

Cheers

Gordon
