### ISSUE TITLE
How to initialize client in php without composer?

### ISSUE THREAD

**Issue by jobs-git** [manticoresoftware/manticoresearch-php#46]
In Sphinx, I usually do it like this

```php
    require('sphinxapi.php');
    $sp = new SphinxClient();
    $sp->SetServer('127.0.0.1',9000);
    $sp->SetArrayResult(true);
    $sp->SetMatchMode(SPH_MATCH_EXTENDED);
```

Now, with manticore 3.5.0, its not working anymore.

**Comment by adriannuta** [comment]
This client has nothing to do with the old sphinxapi client.
It uses the HTTP protocol and  has different classes and methods.

You could use a tiny psr-4 autoloading function , however `Client` has a dependency on `Psr/Log`, so that will need to exists before initializing `Client`.

**Comment by jobs-git** [comment]
Thanks for the response,

I mean, with manticore 3.5.0.

I load files manually, cause I dont want bloat codes like composer in my codes.

Which files are essential that I need to include in php so that I can use the client?

Also, what would be the equivalent for the above code in manticoresearch-php?

**Comment by jobs-git** [comment]
It works with previous version, but until i get the client up, I can't check which code needs revision.

**Comment by jobs-git** [comment]
@klirichek since you mentioned nothing essential has changed, i re-downloaded the old api. Apparently it got caught off when I refactored the whole code. It works now
