### ISSUE TITLE
Including distance value in search results

### ISSUE THREAD

**Issue by jlawrence-yellostudio** [manticoresoftware/manticoresearch-php#47]
Hi Adrian,

I'm not sure if I should be asking this here but thanks in advance!

The distance value of a GEODIST query is not included in the results, can you tell me if this is at all possible using the JSON API or will I have to use SQL to achieve this? e.g. I can do this via SQL

`SELECT *, GEODIST(50.724789, -3.531281, latitude, longitude, {in=deg, out=km}) AS distance FROM myindex`

It's not often I need to display the distance but it would be nice if at all possible to not have to post process the results to recalculate it

My usage:

```
        $searchQuery = new \Manticoresearch\Query\BoolQuery();
        $searchQuery->must(new \Manticoresearch\Query\Distance([
                            'location_anchor'=>
                                ['lat'=>floatval($latitude), 'lon'=> floatval($longitude)],
                            'location_source' => ['latitude', 'longitude'],
                            'location_distance' => '75 mi'
                        ]));
        $search = $index->search($searchQuery);
        $search->sort([
            '_geo_distance' =>[
                'location_anchor'=>
                    ['lat'=>floatval($latitude), 'lon'=> floatval($longitude)],
                'location_source' => [
                    'latitude',
                    'longitude'
                ],
                'order' => 'desc'
            ]
        ]);
        $result = $search->limit($limit)->get();
```

**Comment by adriannuta** [comment]
The current geo distance constructors in HTTP use an internal alias and are not exposed in the result. We have some updates in progress for HTTP and geo_distance will be exposed when it's in a sorting.

You can use an script field with the `GEODIST()` to get the values
```
$search->expression('distance',"GEODIST($latitude, $longitude, latitude_deg, longitude_deg, {in=deg, out=mi})");
```
( I see now Search::expression is not document, I'll add it, it's basically a shorthand for a bool query with [ScriptFields[]](https://github.com/manticoresoftware/manticoresearch-php/blob/master/docs/query.md#scriptfields) ).

You will probably notice that you could just use the GEODIST as expression (instead of the native geo_distance) if you need to get the distance values, like;

```
$searchQuery = new \Manticoresearch\Query\BoolQuery();
$searchQuery->must(new \Manticoresearch\Query\Range('distance', ['lte'=>75]));
$search = $index->search($searchQuery);
$search->expression('distance',"GEODIST($latitude, $longitude, latitude_deg, longitude_deg, {in=deg, out=mi})");
$search->sort('distance','asc');
```
or 
```
$search->filter('distance','lte',75);
$search->expression('distance',"GEODIST($latitude, $longitude, latitude_deg, longitude_deg, {in=deg, out=mi})");
$search->sort('distance','asc');
```

**Comment by jlawrence-yellostudio** [comment]
@adriannuta Thank you kindly for the detail in your response, I have this working now and it simplifies my implementation significantly over falling back to using SQL in this scenario! 

It is worth pointing out to you that in my previous example while attempting to use _geo_distance, where i specify the 'order', it doesn't actually do anything, but it does force it to return the results in the correct order. 

With the order specified as anything, e.g. i could put 'order' => 'foo' it returns the results in the correct order but by default it appears that it returns them in the wrong order. Not sure why that is!

```
        $search->sort([
            '_geo_distance' =>[
                'location_anchor'=>
                    ['lat'=>floatval($latitude), 'lon'=> floatval($longitude)],
                'location_source' => [
                    'latitude',
                    'longitude'
                ],
                'order' => 'foo'
            ]
        ]);
```

**Comment by adriannuta** [comment]
If no order specified, the sort should be ascending (so closest to the geopoint). To get from the farest (limited by the filtering) `order -> desc ` should be specified. 
Which doesn't return the correct sorting?

**Comment by jlawrence-yellostudio** [comment]
For me at least:

```
        $search->sort([
            '_geo_distance' =>[
                'location_anchor'=>
                    ['lat'=>floatval($latitude), 'lon'=> floatval($longitude)],
                'location_source' => [
                    'latitude',
                    'longitude'
                ],
            ]
        ]);
```

As it stands that code returns the furthest away item as the first result, but adding they key 'order' into the '_geo_distance' array seems to make it return the correct order of closest first (even though it doesn't appear to actually pay attention to the value of order at all, can even be a blank string).

Using the other code you have provided to enable me to return distance works perfectly as it's explicitly ordering by the distance expression.

**Comment by adriannuta** [comment]
Sounds like an issue in Manticore (php client send as it is the sorting array).. Better make a ticket in manticore tracker (https://github.com/manticoresoftware/manticoresearch/issues). Does it reproduces on a small index?

**Comment by jlawrence-yellostudio** [comment]
Ok thanks I will and yes it is only 14 items currently!
