### ISSUE TITLE
Match is a reserved word as of PHP 8.0

### ISSUE THREAD

**Issue by henze-housepedia** [manticoresoftware/manticoresearch-php#48]
I stumbled upon it when I got the message: "syntax error, unexpected token \"match\", expecting \":\"""  
I have fiddled around a bit, And it seems renaming the Match object does the trick in fixing it.

**Comment by adriannuta** [comment]
Thanks for reporting this. We will add compatibility for PHP 8.

**Comment by henze-housepedia** [comment]
Is there any information on when this PHP 8 compatibility will be released?

**Comment by sanikolaev** [comment]
> Is there any information on when this PHP 8 compatibility will be released?

This hasn't been planned yet. If php 8 is already in production in your infra and you decide to make a w/a for your personal use (and it's perhaps just about choosing a new name for the match) feel free to make a merge request.

**Comment by adriannuta** [comment]
The `Match` class will be renamed to `MatchQuery`. There is another issue with the default HTTP driver  because of the changes for curl in PHP 8. The  `PhpHttp` driver should work if you update dependencies to use latest Guzzle.

**Comment by adriannuta** [comment]
Added compatibility for PHP 8.0 and released version 1.6.0.
