### ISSUE TITLE
Mva properties are updated via API /json

### ISSUE THREAD

**Issue by zhmm** [manticoresoftware/manticoresearch-php#5]
manticore version：3.3.0 01fc8ad@200204 release

`
$client = new client();
$data = [
    'body' => [
        'index' => 'indexname',
        'id' =>100,
        'doc' => [
            'rent' => '(1,2)',
            'gid' => 26,
        ]
    ]
];
$client->update($data)
`

return：
{"error":{"type":"index indexname: attribute 'rent' MVA flag mismatch","index":"indexname"},"status":500}

How should I write the rent value of mva property?
I tried the following ways：
`1：
'doc'=>[
'rent' => [1,2,3]
]
`
`2：
'doc'=>[
'rent' => '(1,2,3)'
]
`
`
3：
'doc'=>[
'rent' => '[1,2,3]'
]
`
`
4：
'doc'=>[
'rent' => jsone_ncode([1,2,3])
]
`
Return the error message above
I'm freaking out. I don't know what to do
help me   
thanks

**Comment by adriannuta** [comment]
Use array for MVAs and update to Manticore 3.4.0 (there was a bug in 3.3 preventing MVA updates via HTTP)
