### ISSUE TITLE
Unix socket

### ISSUE THREAD

**Issue by mitsh** [manticoresoftware/manticoresearch-php#50]
Hello,

Is there any way to use unix socket connection? 

Regards,

**Comment by sanikolaev** [comment]
Hi

I've discussed it with developers of Manticore Search: 
* In spite of the fact this client is based on Manticore Search's HTTP JSON protocol it should be possible in theory to open a unix socket and write HTTP request into it. 
* But there's no code for that in the php client
* And we haven't tested it in general.

We'll be glad if you give it a try and let us know if it works out. I'm closing the issue for now. Feel free to reopen if needed.

**Comment by mitsh** [comment]
Hi @sanikolaev,

I added UNIX socket capability yesterday, and it works well. I will send a pull request so you can test it.

**Comment by sanikolaev** [comment]
That's great. Thank you!
