### ISSUE TITLE
addDocument() doesn't return inserted "id"

### ISSUE THREAD

**Issue by mitsh** [manticoresoftware/manticoresearch-php#53]
I added a document via PHP but I couldn't manage to get "id" after insert operation.

Array result;
```
Array
(
    [_index] => string "index_name"
    [_id] => integer 0
    [created] => boolean TRUE
    [result] => string "created"
    [status] => integer 201
)
```
I've checked the actual result from SphinxServer. Also, the server didn't give an "id" in the result via HTTP.
```
$ curl -Ss http://localhost:9312/insert -d '{"index":"index_name","doc":{"value":"ze"}}'
{"_index":"index_name","_id":0,"created":true,"result":"created","status":201}
```
Note: "id" has returned in the SQL.

**Comment by adriannuta** [comment]
The problem is not in the PHP Client, but in Manticore - as the client uses HTTP. I suggest to open an issue in the Manticore [tracker](https://github.com/manticoresoftware/manticoresearch/issues).

**Comment by mitsh** [comment]
Ah. Okay, I report them.
