### ISSUE TITLE
Would it be possible to relicense to MIT or BSD?

### ISSUE THREAD

**Issue by marclaporte** [manticoresoftware/manticoresearch-php#69]
This will make it easier to use this lib from within some (L)GPL projects.

Ref: https://github.com/twbs/bootstrap/issues/2054

Specifically, we would like to add support to Tiki Wiki CMS Groupware ([tiki.org](http://tiki.org))

Thanks!

**Comment by sanikolaev** [comment]
Interesting idea. Let us think about it.

**Comment by marclaporte** [comment]
Super! Thank you. Here is some more info:

- https://dev.tiki.org/Manticore-Search
- https://en.wikipedia.org/wiki/License_compatibility#Compatibility_of_FOSS_licenses

**Comment by marclaporte** [comment]
@sanikolaev: work is starting in the next 5-10 days.

We already have an SQL interface to our MySQL storage index and Manticore supports an SQL interface for both indexing and search queries, so we have what we need to bypass the PHP lib if licensing is a problem. Or we could use via https://doc.tiki.org/Packages to make it easy to install. However, I'd prefer if it was built-in. And this is a good change for other projects like Drupal.

If you agree to change the license but we need more time (ex.: contacting previous contributors), we can start the development now and wait for license change before we proceed to an official release.

Thanks!

**Comment by sanikolaev** [comment]
All done. We've switched to MIT.
