### ISSUE TITLE
Indices/Alter.php not working as expected

### ISSUE THREAD

**Issue by tomterl** [manticoresoftware/manticoresearch-php#76]
Using Indices/Alter.php to add a column to an index failes with
```
sphinxql: syntax error, unexpected $undefined, expecting CLUSTER or RTINDEX or TABLE near '+TABLE+test+ADD+COLUMN+benefits+JSON'"
```

If I understand the manticore API documentation correctly, that is expected, because Alter.php extends EmulateBySql.php and that enforces `mode=raw`, but the docs state that 

```
you can set HTTP parameter mode to raw , and then the rest of the query after 'query=' will be passed inside without any substitutions/url decoding
```
So if I'm not mistaken, either the `urlencode` in Sql.php must be skipped if `$k==='query'`, or I'm at a loss at what is supposed to happen, where my misconception lies (Edit: or this is very much a work-in-progress and I should refrain from checking out master if a perfectly good release is there)

**Comment by tomterl** [comment]
Never mind - found the commit message 

cheers

**Comment by sanikolaev** [comment]
Dev version of the php client supports the new behaviour.
