### ISSUE TITLE
URL encoding issue on equals character when passing settings to create index with Manticore 5.0

### ISSUE THREAD

**Issue by jlawrence-yellostudio** [manticoresoftware/manticoresearch-php#92]
Something appears to have changed in 5.0 HTTP, if a value contains an equals sign it is expecting it to be (I assume) double encoded, I haven't checked any raw transmission logs but code that was working on 4.2 no longer works in 5.

Example: 

`http://x.x.x.x:9308/sql?mode=raw&query=CREATE TABLE foobar(title text) rt_mem_limit = '256M'` 

will fail with:

`{
    "error": "query missing"
}`

After some debug, it appears that urlencoding the options fixes the issue, and showing the index settings after reveals that the settings are applied. I'm not sure which other areas of this library are impacted by this.

The fix I have applied locally is to modify line 51 of Endpoints/Indices/Create.php to change:

`                .$options]);`

to: 

`                .urlencode($options)]);`

**Comment by sanikolaev** [comment]
> code that was working on 4.2 no longer works in 5.

Have you updated the php client to 2.1.1?

<img width="585" alt="image" src="https://user-images.githubusercontent.com/28719845/171231141-050d8240-a7f2-47ba-8db0-20fca30e50a5.png">

**Comment by jlawrence-yellostudio** [comment]
Ah @sanikolaev thanks for the quick reply and the answer is no I had 1.8 installed, the composer dependency was locked to the 1.x version, so thanks for pointing that out, I should have probably been a bit more diligent in ensuring it was up to date.
