### ISSUE TITLE
Equals sign in search query breaks request

### ISSUE THREAD

**Issue by DenisAlliswell** [manticoresoftware/manticoresearch-php#96]
Greetings!  
  
Manticore version is **5.0.2 348514c86@220530 dev (columnar 1.15.4 2fef34e@220522) (secondary 1.15.4 2fef34e@220522)**  
  
Index config:  
```  
$index->create([  
    'db_id' => ['type' => 'int'],  
    'name' => ['type' => 'text'],  
], [  
    'min_infix_len' => 2,  
    'index_exact_words' => 1,  
    'expand_keywords' => 1,  
]);  
```  
  
Suppose we have in index text column with value **"Product 123 name="**  
  
The following request  
  
```  
$result = $client->sql([  
    'body' => [  
        'query' => "SELECT * FROM products where MATCH('name=')"  
    ]  
]);  
```  
leads to this error:  
```  
Manticoresearch\Exceptions\ResponseException  
index products: query error: syntax error, unexpected $end near  
```  
  
In [docs](https://manual.manticoresearch.com/Searching/Full_text_matching/Escaping#Escaping-characters-in-query-string) there is no information about escaping equals sign. Escaping it gives an empty result.

**Comment by githubmanticore** [comment]
➤ Nick Sergeev commented:
 

 
This issue has been moved  [here](https://github.com/manticoresoftware/manticoresearch/issues/834)
